on:
  push:
    branches-ignore:
      - master

jobs:
  test:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [ 14.x, 16.x ]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - run: npm ci
      - run: npm run lint:editorconfig
      - run: npm run lint:ts
      - run: npm run lint:scss
      - run: npm run prettier:check
