on:
  push:
    branches-ignore:
      - master

jobs:
  lint:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm
      - run: npm ci
      - run: npm run lint:editorconfig
      - run: npm run lint:ts
      - run: npm run lint:scss
      - run: npm run lint:prettier
  deploy:
    runs-on: ubuntu-20.04
    needs:
      - lint

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Build
        run: |
          npm ci &&
          npm run build
      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r app.zip dist/minimalistic-new-tab
      - name: release
        uses: mnao305/chrome-extension-upload@2.2.0
        with:
          file-path: app.zip
          extension-id: ${{ secrets.EXTENSION_ID }}
          client-id: ${{ secrets.CLIENT_ID }}
          refresh-token: ${{ secrets.REFRESH_TOKEN }}
