on:
  push:
    branches-ignore:
      - master

jobs:
  lint:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm
      - run: npm ci
      - run: npm run lint:editorconfig
      - run: npm run lint:ts
      - run: npm run lint:scss
      - run: npm run lint:prettier
